/**
 * Regenerates server/catalog-generated.js from filamentcolors.xyz.
 *
 * Their swatch library is a public, freely usable community database with an
 * open API, and it tracks far more brands than anyone would want to type out by
 * hand. This runs at development time and commits its output, so the app itself
 * never depends on their site being up — nothing at runtime talks to them.
 *
 * Brands only. Their /filament_type list is per-product marketing names —
 * "Armadillo", "AF80", "Alfasilk", and one literal "???" — rather than material
 * classes, so pulling it in would bury PLA and PETG under vendor SKUs. Material
 * types stay hand-maintained in catalog.js, where they carry print temperatures.
 *
 *   node tools/fetch-catalog.mjs
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const API = 'https://filamentcolors.xyz/api';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'server', 'catalog-generated.js');

/** Walks a paginated DRF endpoint to the end. */
async function fetchAll(path) {
  const rows = [];
  let url = `${API}/${path}/?limit=200`;

  while (url) {
    const res = await fetch(url, { headers: { Accept: 'application/json' } });
    if (!res.ok) throw new Error(`${url} responded ${res.status}`);
    const page = await res.json();
    rows.push(...(page.results ?? []));
    url = page.next;
    process.stderr.write(`  ${path}: ${rows.length}\r`);
  }
  process.stderr.write(`  ${path}: ${rows.length}\n`);
  return rows;
}

const clean = (s) => String(s ?? '').trim();

const manufacturers = await fetchAll('manufacturer');

const brands = [...new Set(manufacturers.map((m) => clean(m.name)).filter(Boolean))]
  .sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));

writeFileSync(OUT, `/**
 * Generated by tools/fetch-catalog.mjs from the filamentcolors.xyz public API.
 * Do not edit by hand — re-run the tool instead. Brands the API doesn't carry
 * go in EXTRA_BRANDS in catalog.js.
 *
 * Source: https://filamentcolors.xyz/api/manufacturer/
 * Retrieved: ${new Date().toISOString().slice(0, 10)}
 */

/** ${brands.length} brands. */
export const GENERATED_BRANDS = [
${brands.map((b) => `  ${JSON.stringify(b)},`).join('\n')}
];
`);

console.log(`Wrote ${brands.length} brands to ${OUT}`);
